-- PokeHuntLog skin database.
-- Generated by tools/build-skins.js from Petopia Classic (https://www.wow-petopia.com/classic/).
-- Do not edit by hand; rerun the script instead.
-- Each skin: family, model, skin id, skin name, then NPCs as
-- { npcId, name, level, zone, tag, attack speed (0 = unknown), ability it knows when tamed }.

PokeHuntLog_Skins = {}

local function add(family, model, id, name, npcs)
  table.insert(PokeHuntLog_Skins, { family = family, model = model, id = id, name = name, npcs = npcs })
end

add("Bat", "Bats", "batskinbrown", "Brown Bat", {
  { 1512, "Duskbat", "1-2", "Tirisfal Glades", "", 2, "" },
  { 1513, "Mangy Duskbat", "3-4", "Tirisfal Glades", "", 2, "" },
  { 1553, "Greater Duskbat", "6-7", "Tirisfal Glades", "", 2, "Cower 1" },
  { 11368, "Bloodseeker Bat", "60", "Zul'Gurub (Raid)", "", 1, "" },
  { 14965, "Frenzied Bloodseeker Bat", "60", "Zul'Gurub (Raid)", "", 1, "" },
})
add("Bat", "Bats", "batskinviolet", "Purple-Red Bat", {
  { 1554, "Vampiric Duskbat", "8-9", "Tirisfal Glades", "", 2, "" },
  { 3866, "Vile Bat", "22-23", "Shadowfang Keep (Dungeon)", "Elite", 2, "" },
  { 8600, "Plaguebat", "53-55", "Eastern Plaguelands", "", 2, "Cower 5 , Dive 3" },
  { 8602, "Monstrous Plaguebat", "56-58", "Eastern Plaguelands", "", 2, "Cower 6 , Screech 4" },
})
add("Bat", "Bats", "batskin", "Tan Bat", {
  { 3868, "Blood Seeker", "23-24", "Shadowfang Keep (Dungeon)", "Elite", 2, "" },
  { 4538, "Kraul Bat", "30-31", "Razorfen Kraul (Dungeon)", "Elite", 2, "Cower 3 , Dive 1" },
  { 4539, "Greater Kraul Bat", "32", "Razorfen Kraul (Dungeon)", "Elite", 2, "Cower 3 , Dive 1" },
  { 4861, "Shrike Bat", "38-39", "Uldaman (Dungeon)", "Elite", 2, "Cower 4 , Dive 1 , Screech 2" },
  { 8927, "Dark Screecher", "50-52", "Blackrock Depths (Dungeon)", "", 2, "Dive 3 , Screech 3" },
  { 8601, "Noxious Plaguebat", "54-56", "Eastern Plaguelands", "", 2, "Cower 5" },
})
add("Bat", "Bats", "batskinwhite", "White Bat", {
  { 10357, "Ressan the Needler", "11", "Tirisfal Glades", "Rare", 2, "" },
  { 4425, "Blind Hunter", "32", "Razorfen Kraul (Dungeon)", "Rare Elite", 2, "" },
})
add("Bear", "Bears", "bearskinblack", "Black Bear", {
  { 1128, "Young Black Bear", "5-6", "Dun Morogh", "", 2, "" },
  { 1129, "Black Bear", "6-7", "Dun Morogh", "", 2.5, "" },
  { 1186, "Elder Black Bear", "11-12", "Loch Modan", "", 2, "" },
  { 1188, "Grizzled Black Bear", "13-14", "Loch Modan", "", 2, "" },
  { 1189, "Black Bear Patriarch", "16-17", "Loch Modan", "", 2, "Claw 3" },
  { 1225, "Ol' Sooty", "20", "Loch Modan", "Elite", 2, "Claw 3" },
  { 14280, "Big Samras", "27", "Hillsbrad Foothills", "Rare", 2, "" },
  { 12037, "Ursol'lok", "31", "Ashenvale", "Rare", 2, "" },
  { 5352, "Old Grizzlegut", "43", "Feralas", "Rare", 2, "Claw 6" },
})
add("Bear", "Bears", "bearskinbrown", "Brown Bear", {
  { 822, "Young Forest Bear", "8-9", "Elwynn Forest", "", 2.5, "Claw 2" },
  { 6789, "Thistle Cub", "9-10", "Darkshore", "", 2, "" },
  { 1778, "Ferocious Grizzled Bear", "11-12", "Silverpine Forest", "", 2, "Claw 2" },
  { 2163, "Thistle Bear", "11-12", "Darkshore", "", 2, "Claw 2" },
  { 12432, "Old Vicejaw", "14", "Silverpine Forest", "Rare", 2, "" },
  { 2165, "Grizzled Thistle Bear", "16-17", "Darkshore", "", 2, "" },
  { 3810, "Elder Ashenvale Bear", "25-26", "Ashenvale", "", 2, "Claw 4" },
  { 3811, "Giant Ashenvale Bear", "29-30", "Ashenvale", "", 2, "" },
  { 14344, "Mongress", "50", "Felwood", "Rare", 2, "Claw 7" },
})
add("Bear", "Bears", "bearskindrkbrown", "Dark Brown Bear", {
  { 1797, "Giant Grizzled Bear", "12-13", "Silverpine Forest", "", 2, "" },
  { 3809, "Ashenvale Bear", "21-22", "Ashenvale", "", 2, "Claw 3" },
})
add("Bear", "Bears", "bearskinblue", "Grey Bear", {
  { 1196, "Ice Claw Bear", "7-8", "Dun Morogh", "", 2, "Claw 1" },
  { 6788, "Den Mother", "18-19", "Darkshore", "", 2, "Claw 3" },
  { 2351, "Gray Bear", "21-22", "Hillsbrad Foothills", "", 2, "Claw 3" },
  { 2354, "Vicious Gray Bear", "22-23", "Hillsbrad Foothills", "", 2, "" },
  { 2356, "Elder Gray Bear", "25-26", "Hillsbrad Foothills", "", 2, "" },
  { 5268, "Ironfur Bear", "41-42", "Feralas", "", 2, "Claw 6" },
  { 5272, "Grizzled Ironfur Bear", "44-45", "Feralas", "", 2, "" },
  { 5274, "Ironfur Patriarch", "48-49", "Feralas", "", 2, "Claw 7" },
  { 7446, "Rabid Shardtooth", "59-60", "Winterspring", "", 2, "" },
})
add("Bear", "Bears", "bearskinblackdiseased", "Sickly Black Bear", {
  { 1815, "Diseased Black Bear", "51-52", "Western Plaguelands", "", 2, "" },
})
add("Bear", "Bears", "bearskindrkbrowndiseased", "Sickly Dark Brown Bear", {
  { 8956, "Angerclaw Bear", "47-48", "Felwood", "", 2, "" },
  { 8958, "Angerclaw Mauler", "49-50", "Felwood", "", 2, "Claw 7" },
  { 8957, "Angerclaw Grizzly", "51-52", "Felwood", "", 2, "" },
  { 1816, "Diseased Grizzly", "55-56", "Western Plaguelands", "", 2, "Claw 7" },
})
add("Bear", "Bears", "bearskinwhite", "White Bear", {
  { 1961, "Mangeclaw", "11", "Dun Morogh", "", 2, "Claw 2" },
  { 1130, "Bjarn", "12", "Dun Morogh", "Rare", 2, "Claw 2" },
  { 7444, "Shardtooth Bear", "53-54", "Winterspring", "", 2, "Claw 7" },
  { 7443, "Shardtooth Mauler", "55-56", "Winterspring", "", 2, "" },
  { 10806, "Ursius", "56", "Winterspring", "Elite", 2.4, "" },
  { 7445, "Elder Shardtooth", "57-58", "Winterspring", "", 2, "Claw 8" },
})
add("Boar", "Boars", "boarskinbluearmored", "Armoured Black Boar", {
  { 4512, "Rotting Agam'ar", "28", "Razorfen Kraul (Dungeon)", "Elite", 2, "Charge 3" },
})
add("Boar", "Boars", "boarskinbrownarmored", "Armoured Brown Boar", {
  { 4511, "Agam'ar", "24-25", "Razorfen Kraul (Dungeon)", "Elite", 2, "Charge 3" },
})
add("Boar", "Boars", "boarskinivoryarmored", "Armoured Pale Boar", {
  { 4514, "Raging Agam'ar", "25-26", "Razorfen Kraul (Dungeon)", "Elite", 2, "Charge 3" },
})
add("Boar", "Boars", "boarskinblue", "Black Boar", {
  { 708, "Small Crag Boar", "3", "Dun Morogh", "", 2, "Charge 1" },
  { 1125, "Crag Boar", "5-6", "Dun Morogh", "", 2, "Charge 1" },
  { 3099, "Dire Mottled Boar", "6-7", "Durotar", "", 2, "Charge 1" },
  { 1126, "Large Crag Boar", "6-7", "Dun Morogh", "", 2, "Charge 1" },
  { 1127, "Elder Crag Boar", "7-8", "Dun Morogh", "", 2, "Charge 1" },
  { 3225, "Corrupted Mottled Boar", "10-11", "Durotar", "", 2, "Charge 1" },
  { 119, "Longsnout", "10-11", "Elwynn Forest", "", 2, "Charge 1" },
  { 8303, "Grunter", "50", "Blasted Lands", "Rare", 2, "Charge 5 , Dash 3" },
})
add("Boar", "Boars", "boarskinbrown", "Brown Boar", {
  { 390, "Porcine Entourage", "7", "Brackwell Pumpkin Patch, Elwynn Forest", "", 2, "Charge 1" },
  { 1190, "Mountain Boar", "10-11", "Loch Modan", "", 2, "Charge 1" },
  { 1192, "Elder Mountain Boar", "16-17", "Loch Modan", "", 2, "Charge 2" },
  { 345, "Bellygrub", "24", "Redridge Mountains", "", 2, "Charge 3" },
})
add("Boar", "Boars", "boarskinundead", "Diseased Boar", {
  { 16117, "Plagued Swine", "60", "Eastern Plaguelands", "", 2, "Charge 6" },
})
add("Boar", "Boars", "boarskinivory", "Pale Boar", {
  { 3098, "Mottled Boar", "1-2", "Durotar", "", 2, "Charge 1" },
  { 524, "Rockhide Boar", "7-8", "Elwynn Forest", "", 2, "Charge 1" },
  { 113, "Stonetusk Boar", "7-8", "Elwynn Forest", "", 2, "Charge 1" },
  { 3100, "Elder Mottled Boar", "8-9", "Durotar", "", 2, "Charge 1" },
  { 1689, "Scarred Crag Boar", "9-10", "Dun Morogh", "", 2, "Charge 1" },
})
add("Boar", "Boars", "boarskincrimson", "Red Boar", {
  { 1985, "Thistle Boar", "2-3", "Teldrassil", "", 2, "Charge 1" },
  { 2954, "Bristleback Battleboar", "4-5", "Mulgore", "", 2, "Charge 1" },
  { 157, "Goretusk", "14-15", "Westfall", "", 2, "Charge 2" },
  { 1191, "Mangy Mountain Boar", "14-15", "Loch Modan", "", 2, "Charge 2" },
  { 547, "Great Goretusk", "16-17", "Redridge Mountains; Westfall", "", 2, "Charge 2" },
  { 5992, "Ashmane Boar", "48-49", "Blasted Lands", "", 2, "Charge 5" },
})
add("Boar", "Boars", "boarskinyellow", "Yellow Boar", {
  { 1984, "Young Thistle Boar", "1-2", "Teldrassil", "", 2, "Charge 1" },
  { 2966, "Battleboar", "3-4", "Mulgore", "", 2, "Charge 1" },
  { 330, "Princess", "9", "Elwynn Forest", "", 2, "Charge 1" },
  { 454, "Young Goretusk", "12-13", "Westfall", "", 2, "Charge 2" },
})
add("Carrion Bird", "Vultures", "carrionbirdskin", "Vulture", {
  { 2969, "Wiry Swoop", "5-7", "Mulgore", "", 2, "" },
  { 2970, "Swoop", "7-9", "Mulgore", "", 2, "" },
  { 2971, "Taloned Swoop", "8-10", "Mulgore", "", 2, "" },
  { 154, "Greater Fleshripper", "16-17", "Westfall", "", 2, "Screech 1" },
  { 2578, "Young Mesa Buzzard", "31-32", "Arathi Highlands", "", 2, "Dive 1" },
  { 2579, "Mesa Buzzard", "34-35", "Arathi Highlands", "", 2, "Dive 1" },
  { 2829, "Starving Buzzard", "35-37", "Badlands", "", 2, "" },
  { 6013, "Wayward Buzzard", "35-37", "Badlands", "", 2, "Dive 1" },
  { 2580, "Elder Mesa Buzzard", "37-38", "Arathi Highlands", "", 2, "" },
  { 2830, "Buzzard", "37-39", "Badlands", "", 2, "" },
  { 2831, "Giant Buzzard", "39-41", "Badlands", "", 2, "" },
  { 5982, "Black Slayer", "46-48", "Blasted Lands", "", 2, "" },
  { 1809, "Carrion Vulture", "50-52", "Western Plaguelands", "", 2, "Dive 3 , Screech 3" },
  { 8299, "Spiteflayer", "52", "Blasted Lands", "Rare", 1.2, "Dive 3" },
})
add("Carrion Bird", "Vultures", "carrionbirdskinblue", "Blue Vulture", {
  { 462, "Vultros", "26", "Westfall", "Rare", 2, "" },
  { 4692, "Dread Swoop", "32-33", "Desolace", "", 2, "" },
  { 4693, "Dread Flyer", "36-37", "Desolace", "", 2, "Dive 1" },
  { 4694, "Dread Ripper", "39-40", "Desolace", "", 2, "Screech 2" },
})
add("Carrion Bird", "Vultures", "carrionbirdskinbrown", "Brown Vulture", {
  { 199, "Young Fleshripper", "10-11", "Westfall", "", 2, "" },
  { 1109, "Fleshripper", "13-14", "Westfall", "", 2, "" },
  { 1194, "Mountain Buzzard", "15-16", "Loch Modan", "", 2, "" },
  { 4154, "Salt Flats Scavenger", "30-32", "Thousand Needles", "", 2, "" },
  { 4158, "Salt Flats Vulture", "32-34", "Thousand Needles", "", 2, "Screech 2" },
  { 4695, "Carrion Horror", "35-37", "Desolace", "", 2, "" },
})
add("Carrion Bird", "Vultures", "carrionbirdskinred", "Red Vulture", {
  { 14268, "Lord Condar", "15-16", "Loch Modan", "Rare", 2, "" },
  { 428, "Dire Condor", "18-19", "Redridge Mountains", "", 2, "" },
  { 5428, "Roc", "42-43", "Tanaris", "", 2, "Dive 2" },
  { 5429, "Fire Roc", "43-45", "Tanaris", "", 2, "Dive 2" },
  { 8207, "Greater Firebird", "46", "Tanaris", "Rare", 2, "Dive 2" },
  { 5430, "Searing Roc", "47-49", "Tanaris", "", 2, "Dive 2" },
  { 2931, "Zaricotl", "55", "Badlands", "Rare Elite", 2, "Dive 3" },
})
add("Cat", "Cats", "tigerskinblack", "Black Cat", {
  { 683, "Young Panther", "30-31", "Stranglethorn Vale", "", 1.3, "Cower 3" },
  { 977, "Kurzen War Panther", "32-33", "Stranglethorn Vale", "", 1.3, "" },
  { 736, "Panther", "32-33", "Stranglethorn Vale", "", 1.3, "Cower 3" },
  { 684, "Shadowmaw Panther", "37-38", "Stranglethorn Vale", "", 1.5, "Prowl 1" },
  { 768, "Shadow Panther", "39-40", "Swamp of Sorrows", "", 1.6, "Prowl 1" },
  { 728, "Bhag'thera", "40", "Stranglethorn Vale", "Elite", 1.5, "Dash 2" },
  { 1713, "Elder Shadowmaw Panther", "42-43", "Stranglethorn Vale", "", 1.5, "Dash 2 , Prowl 2" },
  { 2522, "Jaguero Stalker", "50", "Stranglethorn Vale", "", 2, "Cower 5 , Prowl 3" },
  { 11365, "Zulian Panther", "60", "Zul'Gurub (Raid)", "Elite", 2, "Dash 3" },
  { 15101, "Zulian Prowler", "60", "Zul'Gurub (Raid)", "", 1.6, "" },
})
add("Cat", "Cats", "tigerskindark", "Black-Striped Black Cat", {
  { 2031, "Young Nightsaber", "1", "Teldrassil", "", 2, "" },
  { 2042, "Nightsaber", "5-6", "Teldrassil", "", 1.4, "Cower 1" },
  { 2033, "Elder Nightsaber", "8-9", "Teldrassil", "", 1.4, "" },
  { 2034, "Feral Nightsaber", "10-11", "Teldrassil", "", 1.5, "" },
  { 2175, "Shadowclaw", "13", "Darkshore", "Rare", 1.5, "" },
  { 2071, "Moonstalker Matriarch", "19-20", "Darkshore", "", 1.3, "" },
})
add("Cat", "Cats", "lionessskingold", "Brown & Tan Cat", {
  { 14222, "Araga", "35", "Alterac Mountains", "Rare", 1.4, "" },
})
add("Cat", "Cats", "tigerskinsnow-transparent", "Ghostly Spotted White Cat", {
  { 3619, "Ghost Saber", "19-20", "Ruins of Mathystra, Darkshore", "Spawned", 2, "Claw 3" },
})
add("Cat", "Cats", "tigerskinbrown", "Golden-Tan Cat", {
  { 2961, "Mountain Cougar", "3", "Mulgore", "", 2, "" },
  { 3035, "Flatland Cougar", "7-8", "Mulgore", "", 2, "Cower 1" },
  { 3566, "Flatland Prowler", "9", "Mulgore", "", 2, "" },
  { 3415, "Savannah Huntress", "11-12", "The Barrens", "", 1.5, "" },
  { 3416, "Savannah Matriarch", "17-18", "The Barrens", "", 1.7, "" },
  { 2384, "Starving Mountain Lion", "23-24", "Hillsbrad Foothills", "", 1.2, "Cower 2" },
  { 2385, "Feral Mountain Lion", "27-28", "Hillsbrad Foothills", "", 1.2, "Cower 3" },
  { 4124, "Needles Cougar", "27-28", "Thousand Needles", "", 1.2, "" },
  { 2406, "Mountain Lion", "32-33", "Alterac Mountains", "", 1.4, "Prowl 1" },
  { 2407, "Hulking Mountain Lion", "33-34", "Alterac Mountains", "", 1.4, "" },
  { 2850, "Broken Tooth", "37", "Badlands", "Rare", 1, "Dash 1" },
})
add("Cat", "Cats", "tigerskinblackspotted", "Spotted Black Cat", {
  { 2032, "Mangy Nightsaber", "2", "Teldrassil", "", 2, "" },
  { 2043, "Nightsaber Stalker", "7-8", "Teldrassil", "", 1.4, "" },
  { 14430, "Duskstalker", "9", "Teldrassil", "Rare", 1.4, "" },
  { 4067, "Twilight Runner", "23-24", "Stonetalon Mountains", "", 1.3, "Cower 2" },
})
add("Cat", "Cats", "tigerskinyellow", "Spotted Orange Cat", {
  { 5865, "Dishu", "13", "The Barrens", "Rare", 1.5, "" },
  { 4126, "Crag Stalker", "25-26", "Thousand Needles", "", 1.6, "Cower 3" },
  { 2731, "Ridge Stalker", "36-37", "Badlands", "", 1.3, "Cower 4 , Prowl 1" },
  { 767, "Swamp Jaguar", "36-37", "Swamp of Sorrows", "", 1.2, "Dash 1" },
  { 2732, "Ridge Huntress", "38-39", "Badlands", "", 2, "Cower 4" },
  { 2734, "Ridge Stalker Patriarch", "40-41", "Badlands", "", 1.3, "Dash 2 , Prowl 2" },
})
add("Cat", "Cats", "tigerskinsnow", "Spotted White Cat", {
  { 1199, "Juvenile Snow Leopard", "5-6", "Dun Morogh", "", 1.5, "Cower 1" },
  { 1201, "Snow Leopard", "7-8", "Dun Morogh", "", 2, "" },
})
add("Cat", "Cats", "tigerskinred", "Orange Striped Cat", {
  { 3121, "Durotar Tiger", "7-8", "Durotar", "", 1.3, "Cower 1" },
  { 681, "Young Stranglethorn Tiger", "30-31", "Stranglethorn Vale", "", 1.3, "Cower 3" },
  { 976, "Kurzen War Tiger", "32-33", "Stranglethorn Vale", "", 1.3, "Dash 1" },
  { 682, "Stranglethorn Tiger", "32-33", "Stranglethorn Vale", "", 1.3, "Dash 1" },
  { 1085, "Elder Stranglethorn Tiger", "34-35", "Stranglethorn Vale", "", 1.3, "" },
  { 729, "Sin'Dall", "37", "Stranglethorn Vale", "", 1.3, "Dash 1" },
  { 772, "Stranglethorn Tigress", "37-38", "Stranglethorn Vale", "", 1.3, "" },
  { 11360, "Zulian Cub", "60", "Zul'Gurub (Raid)", "", 2, "" },
  { 11361, "Zulian Tiger", "60", "Zul'Gurub (Raid)", "Elite", 2, "" },
})
add("Cat", "Cats", "tigerskinwhite", "Striped White Cat", {
  { 731, "King Bangalash", "43", "Stranglethorn Vale", "Elite", 1.4, "Claw 6 , Dash 2" },
  { 7431, "Frostsaber", "56-57", "Winterspring", "", 1.5, "" },
})
add("Cat", "Cats", "tigerskinnostripewhite", "White Cat", {
  { 7430, "Frostsaber Cub", "55-56", "Winterspring", "", 1.5, "Cower 6" },
  { 7433, "Frostsaber Huntress", "58-59", "Winterspring", "", 1.5, "Dash 3" },
  { 7432, "Frostsaber Stalker", "59-60", "Winterspring", "", 1.5, "Dash 3 , Prowl 3" },
})
add("Cat", "Cats", "tigerskinblackstriped", "White-Striped Black Cat", {
  { 2070, "Moonstalker Runt", "10-11", "Darkshore", "", 1.3, "Cower 1" },
  { 2069, "Moonstalker", "14-15", "Darkshore", "", 1.3, "" },
  { 2237, "Moonstalker Sire", "17-18", "Darkshore", "", 1.3, "Cower 2" },
})
add("Cat", "Saber Cats", "ridingtigerskinaqua", "Aqua Saber Cat", {
  { 10200, "Rak'Shiri", "57", "Winterspring", "Rare", 1.5, "Dash 3" },
  { 10737, "Shy-Rotam", "60", "Winterspring", "Elite", 1.5, "" },
})
add("Cat", "Saber Cats", "ridingtigerskinlavender", "Lavender Saber Cat", {
  { 7434, "Frostsaber Pride Watcher", "59-60", "Winterspring", "", 1.5, "" },
})
add("Cat", "Lions", "lionskinblack", "Black Lion", {
  { 5828, "Humar The Pridelord", "23", "The Barrens", "Rare", 1.3, "" },
})
add("Cat", "Lions", "lionskingold", "Gold Lion", {
  { 5807, "The Rake", "10", "Mulgore", "Rare", 1.2, "" },
  { 3243, "Savannah Highmane", "12-13", "The Barrens", "", 1.5, "" },
  { 3425, "Savannah Prowler", "14-15", "The Barrens", "", 1.4, "" },
  { 3241, "Savannah Patriarch", "15-16", "The Barrens", "", 1.3, "Cower 2" },
})
add("Cat", "Lions", "lionskinwhite", "White Lion", {
  { 3475, "Echeyakee", "16", "The Barrens", "Spawned", 2, "" },
  { 10741, "Sian-Rotam", "60", "Winterspring", "Spawned Elite", 2, "" },
})
add("Crab", "Crabs", "crabskinsaphire-classic", "Blue Crab", {
  { 2231, "Pygmy Tide Crawler", "9-10", "Darkshore", "", 2, "" },
  { 3228, "Corrupted Surf Crawler", "10-11", "Durotar", "", 2, "" },
  { 2232, "Tide Crawler", "12-14", "Darkshore", "", 2, "Claw 2" },
  { 831, "Sea Crawler", "15-16", "Westfall", "", 2, "" },
  { 2233, "Encrusted Tide Crawler", "18-20", "Darkshore", "", 2, "" },
  { 3812, "Clattering Crawler", "19-20", "Ashenvale", "", 2, "Claw 3" },
  { 2544, "Southern Sand Crawler", "40-41", "Stranglethorn Vale", "", 2, "" },
})
add("Crab", "Crabs", "crabskinbronze-classic", "Bronze Crab", {
  { 830, "Sand Crawler", "13-14", "Westfall", "", 2, "" },
  { 1216, "Shore Crawler", "17-18", "Westfall", "", 2, "Claw 3" },
  { 922, "Silt Crawler", "40-41", "Swamp of Sorrows", "", 2, "Claw 6" },
  { 1088, "Monstrous Crawler", "43-44", "Swamp of Sorrows", "", 2, "Claw 6" },
})
add("Crab", "Crabs", "crabskinvermillian-classic", "Red Crab", {
  { 3106, "Pygmy Surf Crawler", "5-6", "Durotar", "", 2, "Claw 1" },
  { 3107, "Surf Crawler", "7-8", "Durotar", "", 2, "" },
  { 3503, "Silithid Protector", "18-19", "The Barrens", "Spawned", 2, "" },
})
add("Crab", "Crabs", "crabskinivory-classic", "White Crab", {
  { 3108, "Encrusted Surf Crawler", "9-10", "Durotar", "", 2, "Claw 2" },
  { 2234, "Young Reef Crawler", "10-11", "Darkshore", "", 2, "" },
  { 2235, "Reef Crawler", "15-17", "Darkshore", "", 2, "" },
  { 2236, "Raging Reef Crawler", "20-21", "Darkshore", "", 2, "" },
  { 3814, "Spined Crawler", "20-21", "Ashenvale", "", 2, "" },
  { 4821, "Skittering Crustacean", "22-23", "Blackfathom Deeps (Dungeon)", "Elite", 2, "Claw 3" },
  { 4822, "Snapping Crustacean", "23-24", "Blackfathom Deeps (Dungeon)", "Elite", 2, "Claw 3" },
  { 4823, "Barbed Crustacean", "25-26", "Blackfathom Deeps (Dungeon)", "Elite", 2, "Claw 4" },
  { 12347, "Enraged Reef Crawler", "30-32", "Desolace", "", 2, "" },
})
add("Crocolisk", "Crocolisks", "crocodileskinmarsh", "Green Crocolisk", {
  { 1417, "Young Wetlands Crocolisk", "21-22", "Wetlands", "", 2, "" },
  { 1400, "Wetlands Crocolisk", "23-24", "Wetlands", "", 2, "" },
  { 2089, "Giant Wetlands Crocolisk", "25-26", "Wetlands", "", 2, "Bite 4" },
  { 1151, "Saltwater Crocolisk", "35-36", "Stranglethorn Vale", "", 2, "" },
  { 4342, "Drywallow Vicejaw", "36-37", "Dustwallow Marsh", "", 2, "" },
  { 2635, "Elder Saltwater Crocolisk", "38", "Stranglethorn Vale", "Elite", 2, "" },
  { 4344, "Mottled Drywallow Crocolisk", "38-39", "Dustwallow Marsh", "", 2, "Bite 5" },
  { 14233, "Ripscale", "39", "Dustwallow Marsh", "Rare", 2, "Bite 6" },
})
add("Crocolisk", "Crocolisks", "crocodileskinriver", "Grey Crocolisk", {
  { 3110, "Dreadmaw Crocolisk", "9-11", "Durotar", "", 2, "Bite 1" },
  { 1150, "River Crocolisk", "30-31", "Stranglethorn Vale", "", 2, "" },
  { 1152, "Snapjaw Crocolisk", "35-36", "Stranglethorn Vale", "", 2, "" },
  { 15043, "Zulian Crocolisk", "60", "Zul'Gurub (Raid)", "Elite", 2, "" },
})
add("Crocolisk", "Crocolisks", "crocodileskinalbino", "White Crocolisk", {
  { 5053, "Deviate Crocolisk", "18-19", "Wailing Caverns (Dungeon)", "", 2, "Bite 3" },
  { 4841, "Deadmire", "45", "Dustwallow Marsh", "", 2, "Bite 6" },
  { 3581, "Sewer Beast", "50", "Stormwind City", "Rare", 2, "Bite 7" },
})
add("Crocolisk", "Crocolisks", "crocodileskinswamp", "Yellow Crocolisk", {
  { 3231, "Corrupted Dreadmaw Crocolisk", "11-12", "The Barrens", "", 2, "" },
  { 1693, "Loch Crocolisk", "14-15", "Loch Modan", "", 2, "Bite 2" },
  { 2476, "Large Loch Crocolisk", "22", "Loch Modan", "Rare", 2, "Bite 3" },
  { 4341, "Drywallow Crocolisk", "35-36", "Dustwallow Marsh", "", 2, "Bite 5" },
  { 1084, "Young Sawtooth Crocolisk", "35-36", "Swamp of Sorrows", "", 2, "" },
  { 4343, "Drywallow Snapper", "37-38", "Dustwallow Marsh", "", 2, "Claw 5" },
  { 1082, "Sawtooth Crocolisk", "38-39", "Swamp of Sorrows", "", 2, "" },
  { 4345, "Drywallow Daggermaw", "40-41", "Dustwallow Marsh", "", 2, "Bite 6" },
  { 1087, "Sawtooth Snapper", "41-42", "Swamp of Sorrows", "", 2, "Bite 6" },
})
add("Gorilla", "Gorillas", "gorillaskinblack", "Black Gorilla", {
  { 1114, "Jungle Thunderer", "37-38", "Stranglethorn Vale", "", 2, "Thunderstomp 1" },
  { 1516, "Konda", "43", "Spirit Den, Stranglethorn Vale", "Spawned", 2, "" },
  { 2521, "Skymane Gorilla", "50", "Stranglethorn Vale", "", 2, "" },
})
add("Gorilla", "Gorillas", "gorillaskinsilver", "Dark Grey Gorilla", {
  { 1511, "Enraged Silverback Gorilla", "41-42", "Stranglethorn Vale", "", 2, "" },
  { 1558, "Silverback Patriarch", "42-43", "Stranglethorn Vale", "", 2, "" },
  { 6514, "Un'Goro Gorilla", "50-51", "Un'Goro Crater", "", 2, "" },
  { 6513, "Un'Goro Stomper", "51-52", "Un'Goro Crater", "", 2, "" },
  { 6516, "Un'Goro Thunderer", "52-53", "Un'Goro Crater", "", 2, "Thunderstomp 3" },
})
add("Gorilla", "Gorillas", "gorillaskingrey", "Grey Gorilla", {
  { 1108, "Mistvale Gorilla", "32-33", "Stranglethorn Vale", "", 2, "Thunderstomp 1" },
  { 1557, "Elder Mistvale Gorilla", "40-41", "Stranglethorn Vale", "", 2, "Thunderstomp 2" },
})
add("Gorilla", "Gorillas", "gorillaskinred", "Red Gorilla", {
  { 14491, "Kurmokk", "42", "Stranglethorn Vale", "Rare", 2, "" },
  { 5260, "Groddoc Ape", "42-43", "Feralas", "", 2, "" },
  { 5262, "Groddoc Thunderer", "49-50", "Feralas", "", 2, "Thunderstomp 2" },
  { 9622, "U'cha", "55", "Un'Goro Crater", "", 2, "Thunderstomp 3" },
})
add("Gorilla", "Gorillas", "gorillaskinwhite", "White Gorilla", {
  { 6585, "Uhk'loc", "52", "Un'Goro Crater", "Rare", 2, "Bite 7" },
})
add("Hyena", "Hyenas", "hyenaskinblack", "Brown Hyena", {
  { 4250, "Galak Packhound", "24", "Thousand Needles", "", 1.5, "" },
  { 4689, "Starving Bonepaw", "30-32", "Desolace", "", 2, "" },
  { 4688, "Bonepaw Hyena", "33-35", "Desolace", "", 2, "Dash 1" },
  { 4690, "Rabid Bonepaw", "36-38", "Desolace", "", 2, "" },
})
add("Hyena", "Hyenas", "hyenaskinwhite", "Grey Hyena", {
  { 14228, "Giggler", "34", "Desolace", "Rare", 2, "" },
  { 4662, "Magram Bonepaw", "37-38", "Desolace", "", 2, "Dash 1" },
  { 5984, "Starving Snickerfang", "45-46", "Blasted Lands", "", 2, "" },
  { 5985, "Snickerfang Hyena", "49-50", "Blasted Lands", "", 2, "" },
})
add("Hyena", "Hyenas", "hyenaskinoarnge", "Orange Hyena", {
  { 4316, "Kolkar Packhound", "13", "The Barrens", "", 2, "" },
  { 4548, "Steelsnap", "30", "Thousand Needles", "", 2, "" },
  { 5425, "Starving Blisterpaw", "41-42", "Tanaris", "", 2, "Dash 2" },
  { 8208, "Murderous Blisterpaw", "43", "Tanaris", "Rare", 2, "Dash 2" },
  { 5427, "Rabid Blisterpaw", "47-48", "Tanaris", "", 2, "Dash 2" },
})
add("Hyena", "Hyenas", "hyenaskin", "Orange Hyena", {
  { 5426, "Blisterpaw Hyena", "44-45", "Tanaris", "", 2, "Dash 2" },
})
add("Hyena", "Hyenas", "hyenaskinblue", "Purple Hyena", {
  { 5829, "Snort the Heckler", "17", "The Barrens", "Rare", 2, "" },
  { 4248, "Pesterhide Hyena", "26-27", "Thousand Needles", "", 2, "" },
  { 4249, "Pesterhide Snarler", "28-29", "Thousand Needles", "", 2, "" },
  { 8300, "Ravage", "51", "Blasted Lands", "Rare", 1.3, "Dash 3" },
})
add("Hyena", "Hyenas", "hyenaskinred", "Red Hyena", {
  { 4304, "Scarlet Tracking Hound", "33-34", "Scarlet Monastery (Dungeon)", "Elite", 1.5, "Dash 1" },
})
add("Hyena", "Hyenas", "hyenaskinyellow", "Yellow Hyena", {
  { 4127, "Hecklefang Hyena", "15-16", "The Barrens", "", 2, "" },
  { 4129, "Hecklefang Snarler", "18-19", "The Barrens", "", 2, "" },
  { 4128, "Hecklefang Stalker", "22-23", "The Barrens", "", 2, "" },
  { 4660, "Maraudine Bonepaw", "37-38", "Desolace", "Spawned", 2, "" },
})
add("Owl", "Owls", "owlgrey", "Grey Owl", {
  { 1995, "Strigid Owl", "5-6", "Teldrassil", "", 2, "Claw 1" },
  { 1996, "Strigid Screecher", "7-8", "Teldrassil", "", 2, "" },
  { 1997, "Strigid Hunter", "8-9", "Teldrassil", "", 2, "Claw 2" },
  { 7097, "Ironbeak Owl", "48-49", "Felwood", "", 2, "Dive 2 , Screech 3" },
  { 7099, "Ironbeak Hunter", "50-51", "Felwood", "", 2, "Claw 7 , Dive 3" },
  { 7098, "Ironbeak Screecher", "52-53", "Felwood", "", 2, "Dive 3" },
})
add("Owl", "Owls", "owlwhite", "White Owl", {
  { 14343, "Olm the Wise", "52", "Felwood", "Rare", 2, "Claw 7 , Dive 3" },
  { 14283, "Stormpike Owl", "53-54", "Alterac Valley (Battleground)", "Horde only", 2, "" },
  { 7455, "Winterspring Owl", "54-56", "Winterspring", "", 2, "Claw 7 , Dive 3" },
  { 7456, "Winterspring Screecher", "57-59", "Winterspring", "", 2, "Claw 8 , Dive 3 , Screech 4" },
})
add("Raptor", "Raptors", "raptorskinmottledbluegreen", "Blue Raptor", {
  { 3633, "Deviate Slayer", "16-17", "Wailing Caverns (Dungeon)", "Elite", 2, "" },
  { 3637, "Deviate Guardian", "18-19", "Wailing Caverns (Dungeon)", "Elite", 2, "" },
  { 1021, "Mottled Screecher", "24-25", "Wetlands", "", 2, "" },
  { 1023, "Mottled Razormaw", "26-27", "Wetlands", "", 2, "" },
  { 1353, "Sarltooth", "29", "Wetlands", "", 2, "" },
  { 730, "Tethis", "43", "Stranglethorn Vale", "Elite", 2, "" },
})
add("Raptor", "Raptors", "raptorskinmottleddarkgreen", "Green Raptor", {
  { 1022, "Mottled Scytheclaw", "25-26", "Wetlands", "", 2, "" },
  { 854, "Young Jungle Stalker", "36-37", "Stranglethorn Vale", "", 2, "" },
})
add("Raptor", "Raptors", "raptorskingrey", "Grey Raptor", {
  { 3634, "Deviate Stalker", "15-17", "Wailing Caverns (Dungeon)", "Elite", 2, "" },
  { 5842, "Takk the Leaper", "19", "The Barrens", "Rare Elite", 2, "" },
})
add("Raptor", "Raptors", "raptorskinorange", "Orange Raptor", {
  { 1015, "Highland Raptor", "23-24", "Wetlands", "", 2, "" },
  { 1016, "Highland Lashtail", "24-25", "Wetlands", "", 2, "" },
  { 1017, "Highland Scytheclaw", "25-26", "Wetlands", "", 2, "" },
  { 1018, "Highland Razormaw", "27-28", "Wetlands", "", 2, "" },
  { 1019, "Elder Razormaw", "29", "Wetlands", "", 2, "" },
  { 855, "Young Stranglethorn Raptor", "30-31", "Stranglethorn Vale", "", 2, "" },
  { 2560, "Highland Thrasher", "33-34", "Arathi Highlands", "", 2, "" },
  { 685, "Stranglethorn Raptor", "33-34", "Stranglethorn Vale", "", 2, "" },
  { 686, "Lashtail Raptor", "35-36", "Stranglethorn Vale", "", 2, "" },
  { 14232, "Dart", "38", "Dustwallow Marsh", "Rare", 2, "" },
})
add("Raptor", "Raptors", "raptorskinviolet", "Purple Raptor", {
  { 3254, "Sunscale Lashtail", "11-13", "The Barrens", "", 2, "" },
  { 3255, "Sunscale Screecher", "13-15", "The Barrens", "", 2, "" },
  { 3632, "Deviate Creeper", "15-16", "Wailing Caverns (Dungeon)", "Elite", 2, "" },
  { 3256, "Sunscale Scytheclaw", "16-18", "The Barrens", "", 2, "" },
  { 3636, "Deviate Ravager", "18-19", "Wailing Caverns (Dungeon)", "Elite", 2, "" },
  { 1020, "Mottled Raptor", "22-23", "Wetlands", "", 2, "" },
  { 687, "Jungle Stalker", "40-41", "Stranglethorn Vale", "", 2, "" },
})
add("Raptor", "Raptors", "raptorskinred", "Red Raptor", {
  { 3122, "Bloodtalon Taillasher", "6-8", "Durotar", "", 2, "" },
  { 3123, "Bloodtalon Scythemaw", "8-10", "Durotar", "", 2, "" },
  { 3257, "Ishamuhale", "19", "The Barrens", "Spawned", 2, "" },
  { 856, "Young Lashtail Raptor", "33-34", "Stranglethorn Vale", "", 2, "" },
  { 4351, "Bloodfen Raptor", "35-36", "Dustwallow Marsh", "", 2, "" },
  { 4352, "Bloodfen Screecher", "36-37", "Dustwallow Marsh", "", 2, "" },
  { 4355, "Bloodfen Scytheclaw", "37-38", "Dustwallow Marsh", "", 2, "" },
  { 4356, "Bloodfen Razormaw", "39-40", "Dustwallow Marsh", "", 2, "" },
  { 4357, "Bloodfen Lashtail", "40-41", "Dustwallow Marsh", "", 2, "" },
  { 14821, "Razzashi Raptor", "60", "Zul'Gurub (Raid)", "Elite", 2, "" },
})
add("Raptor", "Raptors", "raptorskinyellow", "Yellow Raptor", {
  { 3227, "Corrupted Bloodtalon Scythemaw", "10-11", "Durotar", "", 2, "" },
  { 2559, "Highland Strider", "30-31", "Arathi Highlands", "", 2, "" },
  { 1140, "Razormaw Matriarch", "31", "Wetlands", "Rare", 2, "" },
  { 2561, "Highland Fleshstalker", "36-37", "Arathi Highlands", "", 2, "" },
})
add("Scorpid", "Scorpids", "scorpionskinblack", "Black Scorpid", {
  { 3281, "Sarkoth", "4", "Durotar", "", 2, "Claw 1" },
  { 3226, "Corrupted Scorpid", "10-11", "Durotar", "", 2, "Scorpid Poison 1" },
  { 5823, "Death Flayer", "11", "Durotar", "Rare", 1.6, "Claw 2 , Scorpid Poison 1" },
  { 4139, "Scorpid Terror", "33-34", "Thousand Needles", "", 2, "Scorpid Poison 2" },
  { 7022, "Venomlash Scorpid", "39-40", "Uldaman (Dungeon)", "Elite", 2, "Claw 5" },
  { 5988, "Scorpok Stinger", "50-51", "Blasted Lands", "", 2, "Scorpid Poison 3" },
  { 14476, "Krellack", "56", "Silithus", "Rare", 2, "Scorpid Poison 4" },
})
add("Scorpid", "Scorpids", "scorpionskinyellow", "Bronze Scorpid", {
  { 3126, "Armored Scorpid", "7-8", "Durotar", "", 2, "" },
  { 3127, "Venomtail Scorpid", "9-10", "Durotar", "", 2, "Claw 2 , Scorpid Poison 1" },
  { 9691, "Venomtip Scorpid", "52-53", "Burning Steppes", "", 2, "Scorpid Poison 3" },
  { 9695, "Deathlash Scorpid", "54-55", "Burning Steppes", "", 2, "Claw 7 , Scorpid Poison 3" },
  { 9698, "Firetail Scorpid", "56-57", "Burning Steppes", "", 2, "Scorpid Poison 4" },
})
add("Scorpid", "Scorpids", "scorpionskinbeige", "Brown Scorpid", {
  { 3124, "Scorpid Worker", "3", "Durotar", "", 2, "Claw 1" },
  { 3125, "Clattering Scorpid", "5-6", "Durotar", "", 2, "" },
})
add("Scorpid", "Scorpids", "scorpionskinblue", "Green Scorpid", {
  { 3250, "Silithid Creeper", "20-21", "The Barrens", "", 2, "Scorpid Poison 1" },
  { 3252, "Silithid Swarmer", "21-22", "The Barrens", "", 2, "Scorpid Poison 1" },
})
add("Scorpid", "Scorpids", "scorpionskinpink", "Pink Scorpid", {
  { 5422, "Scorpid Hunter", "40-41", "Tanaris", "", 2, "Claw 6 , Scorpid Poison 3" },
  { 5423, "Scorpid Tail Lasher", "43-44", "Tanaris", "", 2, "Scorpid Poison 3" },
  { 7803, "Scorpid Duneburrower", "46-47", "Tanaris", "Spawned", 2, "Scorpid Poison 3" },
  { 5424, "Scorpid Dunestalker", "46-47", "Tanaris", "", 2, "Scorpid Poison 3" },
})
add("Scorpid", "Scorpids", "scorpionskinred", "Red Scorpid", {
  { 4140, "Scorpid Reaver", "31-32", "Thousand Needles", "", 2, "Claw 4 , Scorpid Poison 2" },
  { 7078, "Cleft Scorpid", "35-36", "Uldaman (Dungeon)", "", 2, "Scorpid Poison 2" },
  { 7405, "Deadly Cleft Scorpid", "42-43", "Uldaman (Dungeon)", "", 2, "Scorpid Poison 3" },
  { 8926, "Deep Stinger", "50-52", "Blackrock Depths (Dungeon)", "", 2, "Scorpid Poison 3" },
})
add("Scorpid", "Scorpids", "scorpionskinsilver", "White Scorpid", {
  { 5937, "Vile Sting", "35", "Thousand Needles", "Rare", 2, "Claw 5 , Scorpid Poison 2" },
  { 8301, "Clack the Reaver", "53", "Blasted Lands", "Rare", 2, "Claw 7" },
  { 11735, "Stonelash Scorpid", "54-55", "Silithus", "", 2, "Scorpid Poison 3" },
  { 11737, "Stonelash Flayer", "58-59", "Silithus", "", 2, "Scorpid Poison 4" },
})
add("Scorpid", "Scorpids", "scorpionskingolden", "Yellow Scorpid", {
  { 4696, "Scorpashi Snapper", "30-31", "Desolace", "", 2, "Claw 4 , Scorpid Poison 2" },
  { 4697, "Scorpashi Lasher", "34-35", "Desolace", "", 2, "Claw 5" },
  { 4699, "Scorpashi Venomlash", "38-39", "Desolace", "", 2, "Scorpid Poison 2" },
  { 11736, "Stonelash Pincer", "56-57", "Silithus", "", 2, "Scorpid Poison 4" },
})
add("Spider", "Tarantulas", "tarantulaskingreen", "Green Tarantula", {
  { 1986, "Webwood Spider", "3-4", "Teldrassil", "", 2, "" },
  { 1994, "Githyiss the Vile", "5", "Teldrassil", "", 2, "Bite 1" },
  { 1998, "Webwood Lurker", "5-6", "Teldrassil", "", 2, "" },
  { 1999, "Webwood Venomfang", "7-8", "Teldrassil", "", 2, "Bite 1" },
  { 2000, "Webwood Silkspinner", "8-9", "Teldrassil", "", 2, "Bite 2" },
  { 2001, "Giant Webwood Spider", "10-11", "Teldrassil", "", 2, "Bite 2" },
  { 1781, "Mist Creeper", "13-14", "Silverpine Forest", "", 2, "" },
  { 4005, "Deepmoss Creeper", "16-17", "Stonetalon Mountains", "", 2, "Bite 3" },
  { 4007, "Deepmoss Venomspitter", "17-18", "Stonetalon Mountains", "", 2, "" },
  { 4006, "Deepmoss Webspinner", "19-20", "Stonetalon Mountains", "", 2, "Bite 3" },
  { 2350, "Forest Moss Creeper", "20-21", "Hillsbrad Foothills", "", 2, "Bite 3" },
  { 4264, "Deepmoss Matriarch", "22", "Stonetalon Mountains", "", 2, "" },
  { 2349, "Giant Moss Creeper", "24-25", "Hillsbrad Foothills", "", 2, "Bite 4" },
  { 3820, "Wildthorn Venomspitter", "24-25", "Ashenvale", "", 2, "" },
  { 769, "Deathstrike Tarantula", "40-41", "Swamp of Sorrows", "", 2, "Bite 6" },
})
add("Spider", "Tarantulas", "tarantulaskingrey", "Grey Tarantula", {
  { 7319, "Lady Sathrah", "12", "Teldrassil", "", 2, "Bite 2" },
  { 14266, "Shanda the Spinner", "19", "Loch Modan", "Rare", 2, "Bite 3" },
  { 3819, "Wildthorn Stalker", "20-21", "Ashenvale", "", 2, "" },
  { 14279, "Creepthess", "24", "Hillsbrad Foothills", "Rare", 2, "Bite 3" },
  { 3821, "Wildthorn Lurker", "28-29", "Ashenvale", "", 2, "Bite 4" },
  { 2563, "Plains Creeper", "32-33", "Arathi Highlands", "", 2, "Bite 5" },
  { 2565, "Giant Plains Creeper", "35-36", "Arathi Highlands", "", 2, "Bite 5" },
  { 1821, "Carrion Lurker", "52-53", "Western Plaguelands", "", 2, "" },
  { 14472, "Gretheer", "57", "Silithus", "Rare", 2, "" },
})
add("Spider", "Tarantulas", "tarantulaskinmagma", "Lava Tarantula", {
  { 5857, "Searing Lava Spider", "45-47", "Searing Gorge", "", 2, "" },
  { 5858, "Greater Lava Spider", "47-49", "Searing Gorge", "", 2, "" },
  { 8277, "Rekk'tilac", "48", "Searing Gorge", "Rare", 2, "Bite 7" },
})
add("Spider", "Tarantulas", "tarantulaskinorange", "Orange Tarantula", {
  { 30, "Forest Spider", "5-6", "Elwynn Forest", "", 2, "Bite 1" },
  { 442, "Tarantula", "15-16", "Redridge Mountains", "", 2, "Bite 2" },
  { 11921, "Besseleth", "21", "Stonetalon Mountains", "Elite", 2, "Bite 3" },
  { 4413, "Darkfang Spider", "35-36", "Dustwallow Marsh", "", 2, "Bite 5" },
  { 4411, "Darkfang Lurker", "36-37", "Dustwallow Marsh", "", 2, "Bite 5" },
  { 858, "Sorrow Spinner", "36-37", "Swamp of Sorrows", "", 2, "" },
  { 4414, "Darkfang Venomspitter", "37-38", "Dustwallow Marsh", "", 2, "" },
  { 4412, "Darkfang Creeper", "38-39", "Dustwallow Marsh", "", 2, "Bite 5" },
  { 4415, "Giant Darkfang Spider", "40-41", "Dustwallow Marsh", "", 2, "" },
})
add("Spider", "Tarantulas", "tarantulaskinbrown", "Red Tarantula", {
  { 1195, "Forest Lurker", "10-11", "Loch Modan", "", 2, "Bite 2" },
  { 1780, "Moss Stalker", "12-13", "Silverpine Forest", "", 2, "" },
  { 1184, "Cliff Lurker", "13-14", "Loch Modan", "", 2, "" },
  { 1185, "Wood Lurker", "17-18", "Loch Modan", "", 2, "Bite 3" },
  { 505, "Greater Tarantula", "19-20", "Redridge Mountains", "", 2, "Bite 3" },
  { 616, "Chatter", "23", "Redridge Mountains", "Rare", 2, "Bite 3" },
  { 2348, "Elder Moss Creeper", "26-27", "Hillsbrad Foothills", "", 2, "Bite 4" },
  { 8762, "Timberweb Recluse", "47-48", "Azshara", "", 2, "Bite 6" },
  { 8933, "Cave Creeper", "50-52", "Blackrock Depths (Dungeon)", "", 2, "Bite 7" },
  { 11738, "Sand Skitterer", "55-56", "Silithus", "", 2, "" },
})
add("Spider", "Spiders", "minespiderskinsteel", "Black Widow Spider", {
  { 1505, "Night Web Spider", "3-4", "Tirisfal Glades", "", 2, "Bite 1" },
  { 1688, "Night Web Matriarch", "5", "Tirisfal Glades", "", 2, "Bite 1" },
  { 43, "Mine Spider", "8-9", "Elwynn Forest", "", 2, "" },
  { 1555, "Vicious Night Web Spider", "9-10", "Tirisfal Glades", "", 2, "Bite 2" },
  { 10359, "Sri'skulk", "13", "Tirisfal Glades", "Rare", 2, "" },
  { 12433, "Krethis Shadowspinner", "15", "Silverpine Forest", "Rare", 2, "" },
  { 930, "Black Widow Hatchling", "24-25", "Duskwood", "", 2, "" },
})
add("Spider", "Spiders", "minespiderskincrystal", "Crystal Spider", {
  { 5856, "Glassweb Spider", "43-45", "Searing Gorge", "", 2, "" },
  { 10375, "Spire Spiderling", "55-56", "Blackrock Spire (Dungeon)", "", 1.5, "" },
})
add("Spider", "Spiders", "minespiderskingreen", "Green Spider", {
  { 471, "Mother Fang", "10", "Elwynn Forest", "Rare", 2, "" },
  { 4263, "Deepmoss Hatchling", "14", "Stonetalon Mountains", "", 2, "" },
  { 569, "Green Recluse", "21-22", "Duskwood", "", 2, "Bite 3" },
  { 949, "Carrion Recluse", "25-26", "Duskwood", "", 2, "" },
  { 4376, "Darkmist Spider", "35-36", "Dustwallow Marsh", "", 2, "" },
  { 4379, "Darkmist Silkspinner", "38-39", "Dustwallow Marsh", "", 2, "" },
})
add("Spider", "Spiders", "minespiderskincave", "Grey Spider", {
  { 539, "Pygmy Venom Web Spider", "18-19", "Duskwood", "", 2, "" },
  { 217, "Venom Web Spider", "19-20", "Duskwood", "", 2, "" },
  { 4040, "Cave Stalker", "21-22", "Wetlands", "", 2, "" },
  { 1112, "Leech Widow", "24", "Wetlands", "Rare", 2, "Bite 4" },
  { 2686, "Witherbark Broodguard", "44-45", "The Hinterlands", "", 2, "" },
  { 1822, "Venom Mist Lurker", "50-51", "Western Plaguelands", "", 2, "" },
  { 14532, "Razzashi Venombrood", "60", "Zul'Gurub (Raid)", "Elite", 2, "" },
})
add("Spider", "Spiders", "minespiderskinjungle", "Jungle Spider", {
  { 4378, "Darkmist Recluse", "36-37", "Dustwallow Marsh", "", 2, "" },
  { 4377, "Darkmist Lurker", "37-38", "Dustwallow Marsh", "", 2, "" },
  { 4380, "Darkmist Widow", "40", "Dustwallow Marsh", "Rare", 2, "" },
})
add("Spider", "Spiders", "minespiderskinolive", "Olive Spider", {
  { 1504, "Young Night Web Spider", "2-3", "Tirisfal Glades", "", 2, "" },
  { 1824, "Plague Lurker", "54-55", "Western Plaguelands", "", 2, "Bite 7" },
})
add("Spider", "Spiders", "minespiderskinblood", "Red Spider", {
  { 574, "Naraxis", "27", "Duskwood", "Rare", 2, "Bite 4" },
})
add("Spider", "Spiders", "minespiderskinwetlands", "Tan Spider", {
  { 1111, "Leech Stalker", "21-22", "Wetlands", "", 2, "" },
  { 11739, "Rock Stalker", "57-58", "Silithus", "", 2, "" },
  { 15041, "Spawn of Mar'li", "60", "Zul'Gurub (Raid)", "", 1.4, "" },
})
add("Tallstrider", "Tallstriders", "tallstriderskinbrown", "Brown Tallstrider", {
  { 2955, "Plainstrider", "1-2", "Mulgore", "", 2, "" },
  { 3244, "Greater Plainstrider", "11-12", "The Barrens", "", 2, "" },
  { 2321, "Foreststrider Fledgling", "11-13", "Darkshore", "", 2, "Cower 1" },
  { 2322, "Foreststrider", "14-16", "Darkshore", "", 2, "" },
  { 2323, "Giant Foreststrider", "17-19", "Darkshore", "", 2, "Cower 2" },
})
add("Tallstrider", "Tallstriders", "tallstriderskingray", "Grey Tallstrider", {
  { 2956, "Adult Plainstrider", "6-7", "Mulgore", "", 2, "" },
  { 3245, "Ornery Plainstrider", "16-17", "The Barrens", "", 1.3, "Cower 2" },
})
add("Tallstrider", "Tallstriders", "tallstriderskinpink", "Pink Tallstrider", {
  { 3068, "Mazzranache", "9", "Mulgore", "Rare", 2, "Cower 1" },
})
add("Tallstrider", "Tallstriders", "tallstriderskinturquoise", "Turquoise Tallstrider", {
  { 2172, "Strider Clutchmother", "20", "Darkshore", "Rare", 2, "" },
})
add("Tallstrider", "Tallstriders", "tallstriderskinivory", "White Tallstrider", {
  { 2957, "Elder Plainstrider", "8-9", "Mulgore", "", 2, "Cower 1" },
  { 3246, "Fleeting Plainstrider", "12-13", "The Barrens", "", 2, "Cower 1" },
})
add("Turtle", "Turtles", "seaturtleskinblue", "Blue Turtle", {
  { 3461, "Oasis Snapjaw", "15-16", "The Barrens", "", 2, "Bite 2" },
  { 3653, "Kresh", "20", "Wailing Caverns (Dungeon)", "Elite", 2, "Bite 3 , Shell Shield 1" },
  { 14123, "Steeljaw Snapper", "42-43", "Tanaris", "", 2, "" },
  { 13599, "Stolid Snapjaw", "46-47", "Maraudon (Dungeon)", "", 2, "" },
  { 5431, "Surf Glider", "48-50", "Tanaris", "", 2, "" },
})
add("Turtle", "Turtles", "seaturtleskin", "Green Turtle", {
  { 4824, "Aku'mai Fisher", "23-24", "Blackfathom Deeps (Dungeon)", "Elite", 2, "Bite 3 , Shell Shield 1" },
  { 2408, "Snapjaw", "30-31", "Hillsbrad Foothills", "", 2, "Bite 4 , Shell Shield 1" },
})
add("Turtle", "Turtles", "seaturtleskingrey", "Grey Turtle", {
  { 4396, "Mudrock Tortoise", "36-37", "Dustwallow Marsh", "", 2, "Bite 5" },
  { 4397, "Mudrock Spikeshell", "37-38", "Dustwallow Marsh", "", 2, "" },
  { 4398, "Mudrock Burrower", "39-40", "Dustwallow Marsh", "", 2, "" },
  { 4400, "Mudrock Snapjaw", "41-42", "Dustwallow Marsh", "", 2, "Bite 6" },
  { 4399, "Mudrock Borer", "42-43", "Dustwallow Marsh", "", 2, "" },
  { 8213, "Ironback", "51", "The Hinterlands", "Rare", 2, "Bite 7" },
})
add("Turtle", "Turtles", "seaturtleskinred", "Orange Turtle", {
  { 4887, "Ghamoo-ra", "25", "Blackfathom Deeps (Dungeon)", "Elite", 2, "Bite 4 , Shell Shield 1" },
  { 4825, "Aku'mai Snapjaw", "26-27", "Blackfathom Deeps (Dungeon)", "Elite", 2, "Bite 4 , Shell Shield 1" },
  { 14223, "Cranky Benj", "32", "Alterac Mountains", "Rare", 2, "Bite 4 , Shell Shield 1" },
  { 2505, "Saltwater Snapjaw", "49-50", "The Hinterlands", "", 2, "Bite 7" },
})
add("Turtle", "Turtles", "seaturtleskinwhite", "White Turtle", {
  { 4142, "Sparkleshell Tortoise", "30-31", "Thousand Needles", "", 2, "" },
  { 4144, "Sparkleshell Borer", "32-33", "Thousand Needles", "", 2, "" },
  { 4143, "Sparkleshell Snapper", "34-35", "Thousand Needles", "", 2, "Bite 5" },
  { 6369, "Coralshell Tortoise", "50-52", "Azshara", "", 2, "" },
  { 6352, "Coralshell Lurker", "53-54", "Azshara", "", 2, "" },
})
add("Wind Serpent", "Wind Serpents", "windserpentskinblack", "Dark Blue Wind Serpent", {
  { 5056, "Deviate Dreadfang", "20-21", "Wailing Caverns (Dungeon)", "Elite", 2, "Lightning Breath 2" },
})
add("Wind Serpent", "Wind Serpents", "windserpentskingreen", "Green Wind Serpent", {
  { 3631, "Deviate Stinglash", "16-17", "Wailing Caverns (Dungeon)", "Elite", 2, "Lightning Breath 2" },
  { 5756, "Deviate Venomwing", "20-21", "Wailing Caverns (Dungeon)", "Elite", 2, "Lightning Breath 2" },
  { 4118, "Venomous Cloud Serpent", "26-28", "Thousand Needles", "", 2, "Lightning Breath 3" },
})
add("Wind Serpent", "Wind Serpents", "windserpentskin", "Orange Wind Serpent", {
  { 3630, "Deviate Coiler", "15-16", "Wailing Caverns (Dungeon)", "Elite", 2, "Lightning Breath 2" },
  { 3247, "Thunderhawk Hatchling", "18-20", "The Barrens", "", 2, "Lightning Breath 2" },
  { 3424, "Thunderhawk Cloudscraper", "20-22", "The Barrens", "", 2, "Lightning Breath 2" },
  { 3249, "Greater Thunderhawk", "23-24", "The Barrens", "", 2, "Lightning Breath 2" },
  { 8336, "Hakkari Sapper", "49-50", "The Temple of Atal'Hakkar (Dungeon)", "Elite", 2, "Lightning Breath 5" },
})
add("Wind Serpent", "Wind Serpents", "windserpentskinred", "Red Wind Serpent", {
  { 5834, "Azzere the Skyblade", "25", "The Barrens", "Rare", 2, "" },
  { 5708, "Spawn of Hakkar", "51", "The Temple of Atal'Hakkar (Dungeon)", "Elite", 2, "Dive 3 , Lightning Breath 5" },
  { 11357, "Son of Hakkar", "60", "Zul'Gurub (Raid)", "Elite", 2, "Lightning Breath 6" },
})
add("Wind Serpent", "Wind Serpents", "windserpentskinred-oarnge", "Red Wind Serpent w/ Orange Wings", {
  { 3472, "Washte Pawne", "25", "The Barrens", "", 2, "Lightning Breath 3" },
  { 10882, "Arikara", "28", "Thousand Needles", "Spawned Elite", 2, "" },
  { 5307, "Vale Screecher", "41-43", "Feralas", "", 2, "Dive 2 , Lightning Breath 4" },
  { 5308, "Rogue Vale Screecher", "44-46", "Feralas", "", 2, "Dive 2 , Lightning Breath 4" },
})
add("Wind Serpent", "Wind Serpents", "windserpentskinwhite", "White Wind Serpent", {
  { 4117, "Cloud Serpent", "25-26", "Thousand Needles", "", 2, "Lightning Breath 3" },
  { 4119, "Elder Cloud Serpent", "27-29", "Thousand Needles", "", 2, "Lightning Breath 3" },
  { 14234, "Hayoc", "41", "Dustwallow Marsh", "Rare", 2, "" },
  { 5349, "Arash-ethis", "49", "Feralas", "Rare", 2, "Dive 2 , Lightning Breath 5" },
  { 5291, "Hakkari Frostwing", "49-50", "The Temple of Atal'Hakkar (Dungeon)", "Elite", 2, "Lightning Breath 5" },
})
add("Wolf", "Wolves", "wolfskinblack", "Black Wolf", {
  { 5356, "Snarler", "42", "Feralas", "Rare", 2, "Bite 6 , Furious Howl 3" },
  { 2680, "Vilebranch Wolf Pup", "46-47", "The Hinterlands", "", 2, "" },
  { 2681, "Vilebranch Raiding Wolf", "50-51", "The Hinterlands", "Elite", 1.7, "Bite 7 , Dash 3" },
})
add("Wolf", "Wolves", "wolfskindiseased", "Diseased Black Wolf", {
  { 8959, "Felpaw Wolf", "47-48", "Felwood", "", 2, "Bite 6 , Furious Howl 3" },
  { 8960, "Felpaw Scavenger", "49-50", "Felwood", "", 2, "" },
  { 8961, "Felpaw Ravager", "51-52", "Felwood", "", 2, "Bite 7" },
  { 1817, "Diseased Wolf", "53-54", "Western Plaguelands", "", 2, "Bite 7" },
})
add("Wolf", "Wolves", "wolfskintimber", "Grey Wolf", {
  { 1508, "Young Scavenger", "1", "Tirisfal Glades", "", 2, "" },
  { 299, "Young Wolf", "1", "Elwynn Forest", "", 2, "" },
  { 69, "Timber Wolf", "2", "Elwynn Forest", "", 2, "" },
  { 1509, "Ragged Scavenger", "2-3", "Tirisfal Glades", "", 2, "Bite 1" },
  { 525, "Mangy Wolf", "5-6", "Elwynn Forest", "", 1.7, "" },
  { 1138, "Snow Tracker Wolf", "6-7", "Dun Morogh", "", 2, "Bite 1" },
  { 1922, "Gray Forest Wolf", "7-8", "Elwynn Forest", "", 1.7, "Bite 1" },
  { 10644, "Mist Howler", "22", "Ashenvale", "Rare", 1.3, "Furious Howl 1" },
  { 5286, "Longtooth Runner", "40-41", "Feralas", "", 2, "Bite 6 , Dash 2 , Furious Howl 3" },
  { 5287, "Longtooth Howler", "43-44", "Feralas", "", 2, "Furious Howl 2" },
  { 5288, "Rabid Longtooth", "47-48", "Feralas", "", 2, "" },
})
add("Wolf", "Wolves", "wolfskinarctic", "Silver-Grey Wolf", {
  { 705, "Ragged Young Wolf", "1", "Dun Morogh", "", 2, "" },
  { 704, "Ragged Timber Wolf", "2", "Dun Morogh", "", 2, "" },
  { 1131, "Winter Wolf", "7-8", "Dun Morogh", "", 2, "Bite 1" },
  { 1133, "Starving Winter Wolf", "8-9", "Dun Morogh", "", 2, "Bite 2" },
  { 3861, "Bleak Worg", "18-19", "Shadowfang Keep (Dungeon)", "Elite", 2, "" },
  { 3823, "Ghostpaw Runner", "19-20", "Ashenvale", "", 2, "Bite 3" },
  { 213, "Starving Dire Wolf", "19-20", "Duskwood", "", 2, "" },
  { 565, "Rabid Dire Wolf", "20-21", "Duskwood", "", 2, "" },
  { 3824, "Ghostpaw Howler", "23-24", "Ashenvale", "", 2, "" },
  { 3825, "Ghostpaw Alpha", "27-28", "Ashenvale", "", 1.3, "Bite 4 , Furious Howl 2" },
})
add("Wolf", "Wolves", "wolfskincoyote", "Tan Wolf", {
  { 2958, "Prairie Wolf", "5-6", "Mulgore", "", 1.5, "Bite 1" },
  { 2959, "Prairie Stalker", "7-8", "Mulgore", "", 1.5, "Bite 1" },
  { 2960, "Prairie Wolf Alpha", "9-10", "Mulgore", "", 1.4, "Bite 2 , Furious Howl 1" },
  { 834, "Coyote", "10-11", "Westfall", "", 2, "Bite 2" },
  { 833, "Coyote Packleader", "11-12", "Westfall", "", 2, "Bite 2 , Furious Howl 1" },
  { 4950, "Spot", "35", "Dustwallow Marsh", "Horde only", 2, "Dash 1" },
  { 2727, "Crag Coyote", "35-36", "Badlands", "", 2, "Bite 5 , Dash 1" },
  { 2728, "Feral Crag Coyote", "37-38", "Badlands", "", 2, "Dash 1" },
  { 2729, "Elder Crag Coyote", "39-40", "Badlands", "", 2, "Dash 1 , Furious Howl 2" },
  { 2730, "Rabid Crag Coyote", "42-43", "Badlands", "", 2, "Dash 2" },
})
add("Wolf", "Worgs", "direwolfskindarkblack", "Black Worg", {
  { 1765, "Worg", "10-11", "Silverpine Forest", "", 2, "Bite 2 , Furious Howl 1" },
  { 1766, "Mottled Worg", "11-12", "Silverpine Forest", "", 2, "" },
  { 1923, "Bloodsnout Worg", "16-17", "Silverpine Forest", "", 2, "Bite 3" },
  { 3862, "Slavering Worg", "18-19", "Shadowfang Keep (Dungeon)", "Elite", 1.2, "" },
  { 923, "Young Black Ravager", "23-24", "Duskwood", "", 2, "" },
  { 2275, "Enraged Stanley", "24", "Hillsbrad Foothills", "Spawned", 1.3, "" },
  { 628, "Black Ravager", "24-25", "Duskwood", "", 2, "Bite 4" },
  { 1258, "Black Ravager Mastiff", "25-26", "Duskwood", "", 2, "Bite 4 , Furious Howl 2" },
  { 10221, "Bloodaxe Worg Pup", "52-53", "Blackrock Spire (Dungeon)", "", 2, "" },
  { 10077, "Deathmaw", "53", "Burning Steppes", "Rare", 1.2, "" },
  { 7055, "Blackrock Worg", "54-55", "Burning Steppes", "", 2, "Dash 3" },
  { 9696, "Bloodaxe Worg", "56-57", "Blackrock Spire (Dungeon)", "", 1.5, "Bite 8 , Dash 3 , Furious Howl 4" },
})
add("Wolf", "Worgs", "direwolfskindarkgrey", "Dark Grey Worg", {
  { 8211, "Old Cliff Jumper", "42", "The Hinterlands", "Rare", 2, "Bite 6 , Dash 2" },
})
add("Wolf", "Worgs", "direwolfskinlightgrey", "Light Grey Worg", {
  { 118, "Prowler", "9-10", "Elwynn Forest", "", 1.5, "Bite 2" },
  { 12431, "Gorefang", "13", "Silverpine Forest", "Rare", 2, "" },
  { 2923, "Mangy Silvermane", "41-42", "The Hinterlands", "", 2, "" },
  { 2924, "Silvermane Wolf", "43-44", "The Hinterlands", "", 2, "Furious Howl 3" },
  { 2925, "Silvermane Howler", "45-46", "The Hinterlands", "", 2, "Furious Howl 2" },
  { 2926, "Silvermane Stalker", "47-48", "The Hinterlands", "", 2, "Dash 2" },
})
add("Wolf", "Worgs", "direwolfskinreddishbrown", "Red Worg", {
  { 2753, "Barnabus", "38", "Badlands", "Rare", 2, "Bite 6" },
  { 9690, "Ember Worg", "51-52", "Burning Steppes", "", 2, "" },
  { 9416, "Scarshield Worg", "53-54", "Blackrock Spire (Dungeon)", "", 1.5, "Dash 3" },
  { 9694, "Slavering Ember Worg", "53-54", "Burning Steppes", "", 2, "" },
  { 9697, "Giant Ember Worg", "55-56", "Burning Steppes", "", 2, "" },
})
add("Wolf", "Worgs", "direwolfskinlightblue", "Silver-Grey Worg", {
  { 1132, "Timber", "10", "Dun Morogh", "Rare", 2, "Bite 2" },
  { 521, "Lupos", "23", "Duskwood", "Rare", 2, "Bite 3" },
  { 14339, "Death Howl", "49", "Felwood", "Rare", 2, "Bite 6 , Furious Howl 3" },
  { 10981, "Frostwolf", "50-51", "Alterac Valley (Battleground)", "", 2, "" },
})
