-- PokeHuntLog family data: Petopia's family role, stat modifiers, trainable abilities and diet.
-- Generated by tools/build-skins.js from Petopia Classic (https://www.wow-petopia.com/classic/).
-- Do not edit by hand; rerun the script instead.

PokeHuntLog_Families = {
  ["Bat"] = {
    role = "Offense", health = 1, armor = 1, damage = 1.07,
    abilities = { "Bite", "Cower", "Dive", "Growl", "Screech" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Fruit", "Fungus" },
  },
  ["Bear"] = {
    role = "Defense", health = 1.08, armor = 1.05, damage = 0.91,
    abilities = { "Bite", "Claw", "Cower", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Bread", "Cheese", "Fish", "Fruit", "Fungus", "Meat" },
  },
  ["Boar"] = {
    role = "Defense", health = 1.04, armor = 1.09, damage = 0.9,
    abilities = { "Bite", "Charge", "Cower", "Dash", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Bread", "Cheese", "Fish", "Fruit", "Fungus", "Meat" },
  },
  ["Carrion Bird"] = {
    role = "General", health = 1, armor = 1.05, damage = 1,
    abilities = { "Bite", "Claw", "Cower", "Dive", "Growl", "Screech" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Fish", "Meat" },
  },
  ["Cat"] = {
    role = "Offense", health = 0.98, armor = 1, damage = 1.1,
    abilities = { "Bite", "Claw", "Cower", "Dash", "Growl", "Prowl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Fish", "Meat" },
  },
  ["Crab"] = {
    role = "Defense", health = 0.96, armor = 1.13, damage = 0.95,
    abilities = { "Claw", "Cower", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Bread", "Fish", "Fruit", "Fungus" },
  },
  ["Crocolisk"] = {
    role = "Defense", health = 0.95, armor = 1.1, damage = 1,
    abilities = { "Bite", "Cower", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Fish", "Meat" },
  },
  ["Gorilla"] = {
    role = "Defense", health = 1.04, armor = 1, damage = 1.02,
    abilities = { "Bite", "Cower", "Growl", "Thunderstomp" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Fruit", "Fungus" },
  },
  ["Hyena"] = {
    role = "General", health = 1, armor = 1.05, damage = 1,
    abilities = { "Bite", "Cower", "Dash", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Fruit", "Meat" },
  },
  ["Owl"] = {
    role = "Offense", health = 1, armor = 1, damage = 1.07,
    abilities = { "Claw", "Cower", "Dive", "Growl", "Screech" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Meat" },
  },
  ["Raptor"] = {
    role = "Offense", health = 0.95, armor = 1.03, damage = 1.1,
    abilities = { "Bite", "Claw", "Cower", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Meat" },
  },
  ["Scorpid"] = {
    role = "Defense", health = 1, armor = 1.1, damage = 0.94,
    abilities = { "Claw", "Cower", "Growl", "Scorpid Poison" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Meat" },
  },
  ["Spider"] = {
    role = "Offense", health = 1, armor = 1, damage = 1.07,
    abilities = { "Bite", "Cower", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Meat" },
  },
  ["Tallstrider"] = {
    role = "Defense", health = 1.05, armor = 1, damage = 1,
    abilities = { "Bite", "Cower", "Dash", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Cheese", "Fruit", "Fungus" },
  },
  ["Turtle"] = {
    role = "Defense", health = 1, armor = 1.13, damage = 0.9,
    abilities = { "Bite", "Cower", "Growl", "Shell Shield" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Fish", "Fruit", "Fungus" },
  },
  ["Wind Serpent"] = {
    role = "Offense", health = 1, armor = 1, damage = 1.07,
    abilities = { "Bite", "Cower", "Dive", "Growl", "Lightning Breath" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Bread", "Cheese", "Fish" },
  },
  ["Wolf"] = {
    role = "General", health = 1, armor = 1.05, damage = 1,
    abilities = { "Bite", "Cower", "Dash", "Furious Howl", "Growl" },
    passives = { "Arcane Resistance", "Fire Resistance", "Frost Resistance", "Great Stamina", "Natural Armor", "Nature Resistance", "Shadow Resistance" },
    diet = { "Meat" },
  },
}
